version: "3"

services:
  hoshino:
    image: pcrbot/hoshinobot:latest
    networks:
      - qqbot
    volumes:
      - ./Hoshino:/HoshinoBot
  gocqhttp:
    image: pcrbot/gocqhttp:0.9.31-fix2-ffmpeg
    networks:
      - qqbot
    volumes:
      - ./gocqhttp_data:/data
      - ./Hoshino:/HoshinoBot
  #yobot:
  #  image: yobot/yobot:pypy
  #  ports:
  #    - "9222:9222"
  #  networks:
  #    - qqbot
  #  volumes:
  #    - ./yobot_data:/yobot/yobot_data

networks:
  qqbot:
    driver: bridge
