name: Build hoshinobot image
on: workflow_dispatch
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Hoshinobot Image
        uses: docker/build-push-action@v1
        with:
          username: pcrbot
          password: ${{ secrets.PCRBOT_DOCKER_TOKEN }}
          repository: pcrbot/hoshinobot
          dockerfile: hoshinobot/Dockerfile
          tags: latest
